### ISSUE TITLE
sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by lmxliumingxiao** [mattn/go-sqlite3#335]
Cross compiled on the windows, running on the Linux on the error, the Linux directly compiled is normal, there is no other people have encountered such a situation, the solution, thank you

**Comment by inputusernamehere** [comment]
Try adding this to your imports:
`
_ "github.com/mattn/go-sqlite3"`

**Comment by MasterDimmy** [comment]
The same issue: 

I got
"ERROR: sql: unknown driver "sqlite3" (forgotten import?)"

Code of imports:

import (
	"database/sql"	
	"github.com/go-gorp/gorp"	
	_ "github.com/mattn/go-sqlite3"	
)

**Comment by mattn** [comment]
please show me `go env`

**Comment by MasterDimmy** [comment]
Local OS: Windows 7 x64.
I build for Linux Ubuntu.

I compile with script:

//windows site:
M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\go\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=o:\temp\go-build442103462=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go build

now i got fully workable project for Windows x64 with go-sqlite3 included and worked ok.

then i prepare for building for linux.

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>set GOARCH=386
M:\Projects\FL\CURRENT_Browser\BrowserTrapper>set GOOS=linux

now go env is 

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go env
set GOARCH=386
set GOBIN=
set GOEXE=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=c:\go\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-fPIC -m32 -fmessage-length=0 -fdebug-prefix-map=o:\temp\go-build189655042=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=0

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go build

then it builds successfully linux executable
but when i copy it to ubuntu and ran i got

 "ERROR: sql: unknown driver "sqlite3" (forgotten import?)"

I have tryed to do so:
import (
	sq "github.com/mattn/go-sqlite3"
)

And added
var Nothing int = 0 
into you lib code,

Then in my code:
	if sq.Nothing == 1 { //never happens, for linux compiling
		return nil, nil
	}

so i think, that forces to include sqlite3 library to the linux code, but it still writes
 "ERROR: sql: unknown driver "sqlite3" (forgotten import?)"

Can it be because i compile for linux/386 from non-linux x64 host compiler?
set GOHOSTARCH=amd64
set GOARCH=386

**Comment by mattn** [comment]
Do you use cross C compiler for the Linux?

**Comment by MasterDimmy** [comment]
Nope.
I use just pure go

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go version
go version go1.7.4 windows/amd64

and nothing else.
All commands i ran - you saw before.
Just pure go 1.7.4 for Windows x64.

**Comment by mattn** [comment]
go-sqlite3 is cgo module. so you need to install cross C compiler.

**Comment by MasterDimmy** [comment]
i have msys64 on system, so i think, it uses its cgo.
when i removed msys64 i got 

M:\Projects\FL\CURRENT_Browser\BrowserTrapper>go get  -u github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

Here 
https://github.com/mattn/go-sqlite3/issues/212#issuecomment-112824993
you wrote that i can build without gcc, but i doesnt help.

Which cross compiler should i use? Did you test any for such situation?

**Comment by MasterDimmy** [comment]
Also tried to complile with https://github.com/mitchellh/gox
Doesn't help.

C:\msys64\mingw64\bin>gcc.exe --version
gcc.exe (Rev1, Built by MSYS2 project) 5.3.0

**Comment by mattn** [comment]
your `go env` and gcc.exe seems not cross compiler.

**Comment by MasterDimmy** [comment]
But other part works well.
The whole my program output is:

root@ubuntu-1gb-nyc1-01-TRAPPER-1:/home/trapper# ./btt
Usage of ./btt:
  -admin
        For debug: guest is admin
  -cache
        Use build-in caching (default true)
TAKEN VALUES:
Use build-in caching: true
For debug: guest is admin: false
ERROR: sql: unknown driver "sqlite3" (forgotten import?)

- so it runs ok, but doesnt see sqlite3. 
Which cross-compiler for windows works ok for go-sqlite3?

**Comment by mattn** [comment]
>But other part works well.
Yes, this is behavior of go and cgo. When missing cross environment. For example, os/user package is using cgo. So if you create executable using os/user with cross compiling, user.Current() return always nil.

**Comment by sourcesoft** [comment]
@mattn I'm using go on OSX and trying to compile for windows. What cross-compiler could I use? Could you guide me to the right direction

**Comment by mattn** [comment]
In generally, go can build Windows executable from Linux or OSX. But when the package is using cgo, you need to install cross C compiler.

**Comment by sourcesoft** [comment]
I'm now to Go and it's compiler. How could install cross C compiler for it? should I use `CC=gcc` for `go build`? thanks

**Comment by mattn** [comment]
Sorry, I'm not OSX user. So I don't know.

**Comment by sourcesoft** [comment]
I figured out a way for compiling from OSX targeting windows with CGO enabled and gave an answer here: http://stackoverflow.com/a/42299401/777329

Thank you for your wonderful library.

**Comment by Alireza-Ghavabesh** [comment]
> Try adding this to your imports: ` _ "github.com/mattn/go-sqlite3"`

fixed my problem, tnx.

**Comment by tiagofrancafernandes** [comment]
> > Try adding this to your imports: ` _ "github.com/mattn/go-sqlite3"`
> 
> fixed my problem, tnx.

me too, thanks

**Comment by bupd** [comment]
Still an issue, Why not add it to the main documentation.  tho
