### ISSUE TITLE
When using v1.14.1, go get -u ./... wants to fetch v2.0.6+incompatible and fails

### ISSUE THREAD

**Issue by marianrh** [mattn/go-sqlite3#844]
Hi,

my `go.mod` contains:
`github.com/mattn/go-sqlite3 v1.14.1`

When doing `go get -u ./...` to upgrade all dependencies in my project, go says:
```
go: finding github.com/mattn/go-sqlite3 v2.0.6+incompatible
verifying github.com/mattn/go-sqlite3@v2.0.6+incompatible/go.mod: github.com/mattn/go-sqlite3@v2.0.6+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/mattn/go-sqlite3@v2.0.6+incompatible: 410 Gone
```

I'm not sure whether this is a problem in my setup (I already cleared the Go modules caches using `go clean -modcache`), or whether the Go sumdb has invalid data or whether the tags in this project are weird somehow.

Thanks,
Marian

**Comment by marianrh** [comment]
The problem above seems to occur when using the JFrog GoCenter proxy (https://search.gocenter.io/).

However, when using no proxy at all the situation is still not right. Without a proxy, `go get -u ./...` tries to upgrade to v2.0.3+incompatible:
```
go: finding github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: extracting github.com/mattn/go-sqlite3 v2.0.3+incompatible
```
This does not fail, but is still unexpected.

I'd be glad for any input!

**Comment by marianrh** [comment]
Ok, it seems that this should be fixed in Go 1.14 (I'm using 1.13) according to https://github.com/golang/go/issues/33558#issuecomment-555063032.

**Comment by jtherin** [comment]
Still get `github.com/mattn/go-sqlite3 v2.0.3+incompatible` with Go 1.15.2
